# ============================================================================
# 01_recorder.R — THE shared step recorder (house rules 6 + 8, one mechanism)
#
# Every analysis stage in every tab registers {id, phase, description, code}.
# Re-running a stage upserts by id, so the exported R script (rule 6) and the
# plain-language pipeline log (rule 8) always reflect current state and can
# never drift apart: both are rendered from the same list.
#
# DECISION: one app-wide recorder instance, not one per tab — rules 6+8 demand
#   a single exported script/log describing everything the app did.
# DECISION: fragments are ordered by PHASE first, insertion order second, so
#   the exported script always runs top-to-bottom in a clean session even if
#   the user hopped between tabs in a strange order.
# DECISION: each stochastic fragment re-emits set.seed(<seed>) immediately
#   before its own boot/resample call (not once at the top), so a colleague
#   sourcing the script reproduces the app's numbers regardless of which
#   stages they re-run and in what order.
# DECISION: tab analysis fragments must bake in their own variable subset
#   (explicit c("V1","V2",...)), never reference the live varselect step —
#   otherwise editing the selection after running tab A silently changes
#   what tab A's exported code means.
# ============================================================================

# Fixed phase order for script assembly. Within a phase, insertion order.
REC_PHASES <- c("setup", "data", "reshape", "varselect",
                "analysis", "stability", "comparison", "plot", "export")

new_recorder <- function(seed = 12345L) {
  rec <- new.env(parent = emptyenv())
  rec$steps <- list()                 # keyed by id
  rec$order <- character(0)           # insertion order of ids
  rec$seed  <- as.integer(seed)
  rec$rev   <- shiny::reactiveVal(0L) # bump to invalidate dependent UI
  rec
}

rec_seed <- function(rec) rec$seed

rec_set_seed <- function(rec, seed) {
  rec$seed <- as.integer(seed)
  rec_touch(rec)
}

rec_touch <- function(rec) {
  rec$rev(shiny::isolate(rec$rev()) + 1L)
  invisible(rec)
}

# Register or update a step. `code` is plain R that reproduces the stage in a
# clean session; `description` is one plain-language sentence for the log.
rec_upsert <- function(rec, id, phase, description, code) {
  stopifnot(phase %in% REC_PHASES)
  if (!(id %in% rec$order)) rec$order <- c(rec$order, id)
  rec$steps[[id]] <- list(id = id, phase = phase,
                          description = description,
                          code = code, time = Sys.time())
  rec_touch(rec)
}

rec_drop <- function(rec, ids) {
  ids <- intersect(ids, rec$order)
  if (!length(ids)) return(invisible(rec))
  rec$steps[ids] <- NULL
  rec$order <- setdiff(rec$order, ids)
  rec_touch(rec)
}

# Drop every step whose id starts with `prefix`. Used when an upstream stage
# invalidates downstream ones (e.g. new data upload voids all analyses).
rec_drop_prefix <- function(rec, prefix) {
  rec_drop(rec, rec$order[startsWith(rec$order, prefix)])
}

# Ordered step list: phase order, then insertion order (explicitly stable).
rec_ordered <- function(rec) {
  steps <- rec$steps[rec$order]
  if (!length(steps)) return(steps)
  ph <- match(vapply(steps, `[[`, "", "phase"), REC_PHASES)
  steps[order(ph, seq_along(steps))]
}

# Rule 6: standalone R script. Header = library() calls + exact package
# versions + timestamp; body = every fragment's code in phase order.
build_script <- function(rec, pkgs, versions, app_name = "Merged network app") {
  steps <- rec_ordered(rec)
  header <- c(
    paste0("# Reproducible analysis script — generated by ", app_name),
    paste0("# Generated: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z")),
    paste0("# Master seed: ", rec$seed,
           " (re-set before every stochastic step below)"),
    "#",
    "# Package versions at generation time (house rule 0):",
    sprintf("#   %-24s %s", pkgs, versions),
    "",
    sprintf("library(%s)", pkgs),
    ""
  )
  body <- unlist(lapply(steps, function(s) {
    c(sprintf("## ---- [%s] %s ----", s$phase, s$id),
      sprintf("## %s", s$description),
      s$code, "")
  }))
  paste(c(header, body), collapse = "\n")
}

# Rule 8: ordered plain-language pipeline log, same source of truth.
build_pipeline_log <- function(rec) {
  steps <- rec_ordered(rec)
  if (!length(steps)) return("No analysis steps recorded yet.")
  lines <- vapply(seq_along(steps), function(i) {
    s <- steps[[i]]
    sprintf("%2d. [%s] %s  (last run: %s)",
            i, s$phase, s$description, format(s$time, "%H:%M:%S"))
  }, "")
  paste(lines, collapse = "\n")
}

# Convenience: run expr with the recorder's seed (app-side twin of the
# `set.seed(<seed>)` line each fragment emits — keeps app and script in sync).
with_rec_seed <- function(rec, expr) {
  set.seed(rec$seed)
  force(expr)
}
